site_name: PenguinOps Docs
site_url: https://macs-massimopiazza.github.io/live-coding-mkdocs/

theme:
  # name: shadcn
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid