site_name: Nome della tua Documentazione
site_url: https://macs-massimopiazza.github.io/live-coding-mkdocs/

theme:
  name: shadcn

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid