name: We we

# Trigger, quando far partire l'action. Push ad ogni push, workflow_dispatch per farla eseguire a comando da GH
on:
  push:
  workflow_dispatch:


# specifico cosa deve fare l'action
jobs:
  test-base:
    # setup ambiente di sviluppo (VM ubuntu)
    runs-on: ubuntu-latest
    
    # step che deve seguire il job
    steps:
      # scarica il codice della repo sulla VM
      - name: Checkout del codice
        uses: actions/checkout@v4

      # qua stampo in console un saluto
      - name: Saluta l'utente
        run: echo "Ciao ${{ github.actor }}! Hai appena fatto un push."

      # lancio in vm comando per mostrare tutti i file
      - name: Verifica presenza file
        run: |
          echo "Ecco i file scaricati nella macchina virtuale:"
          ls -la
      - name: Attesa di 10 secondi
        run: sleep 10s
        shell: bash